export interface GameTemplate {
  id: string;
  name: string;
  nameAr: string;
  emoji: string;
  description: string;
  topic: string; // chemistry topic it suits
  bg: string;           // main background gradient
  cardBg: string;       // question card bg
  choiceColors: string[]; // 4 answer button colors
  accentColor: string;
  textColor: string;
  timerColor: string;
  headerBg: string;
  particles: string[];  // floating emoji decorations
  font?: string;
  badge: string;        // topic badge emoji
}

export const TEMPLATES: GameTemplate[] = [
  {
    id: 'periodic-table',
    name: 'Periodic Table Lab',
    nameAr: 'مختبر الجدول الدوري',
    emoji: '🔬',
    description: 'Dark scientific lab with periodic table elements floating around',
    topic: 'General Chemistry',
    bg: 'linear-gradient(135deg, #0a0a1a 0%, #0d1b2a 50%, #1a0a2e 100%)',
    cardBg: 'rgba(13,27,42,0.9)',
    choiceColors: ['#3b82f6', '#8b5cf6', '#06b6d4', '#6366f1'],
    accentColor: '#60a5fa',
    textColor: '#e2e8f0',
    timerColor: '#60a5fa',
    headerBg: 'rgba(10,10,26,0.95)',
    particles: ['H', 'He', 'Li', 'C', 'N', 'O', 'Na', 'Mg', 'Al', 'Si', 'Cl', 'K', 'Ca', 'Fe', 'Cu', 'Zn', 'Br', 'Au'],
    badge: '⚛️',
  },
  {
    id: 'organic-chemistry',
    name: 'Organic World',
    nameAr: 'عالم الكيمياء العضوية',
    emoji: '🌿',
    description: 'Green organic theme with carbon chains and molecular structures',
    topic: 'Organic Chemistry',
    bg: 'linear-gradient(135deg, #052e16 0%, #14532d 50%, #166534 100%)',
    cardBg: 'rgba(5,46,22,0.9)',
    choiceColors: ['#22c55e', '#16a34a', '#4ade80', '#86efac'],
    accentColor: '#4ade80',
    textColor: '#dcfce7',
    timerColor: '#4ade80',
    headerBg: 'rgba(5,46,22,0.95)',
    particles: ['CH₄', 'C₂H₆', '-OH', '-COOH', '-CHO', 'C=C', 'C≡C', 'R-', 'C₆H₆', 'CH₃'],
    badge: '🌿',
  },
  {
    id: 'fire-reactions',
    name: 'Reaction Fire',
    nameAr: 'نار التفاعلات',
    emoji: '🔥',
    description: 'Hot fiery theme for exothermic reactions and energy topics',
    topic: 'Thermodynamics / Reactions',
    bg: 'linear-gradient(135deg, #1c0500 0%, #7c1d06 50%, #c2410c 100%)',
    cardBg: 'rgba(28,5,0,0.92)',
    choiceColors: ['#ef4444', '#f97316', '#eab308', '#dc2626'],
    accentColor: '#fb923c',
    textColor: '#fef3c7',
    timerColor: '#fbbf24',
    headerBg: 'rgba(28,5,0,0.97)',
    particles: ['🔥', '💥', '⚡', '🌡️', '♨️', '🔥', '💨', '✨', '🌋', '⚗️'],
    badge: '🔥',
  },
  {
    id: 'ocean-acids',
    name: 'Ocean pH Lab',
    nameAr: 'مختبر الأحماض والقواعد',
    emoji: '🌊',
    description: 'Deep ocean blue for acids, bases and pH topics',
    topic: 'Acids & Bases',
    bg: 'linear-gradient(135deg, #0c1445 0%, #1e3a5f 50%, #0e4d7b 100%)',
    cardBg: 'rgba(12,20,69,0.9)',
    choiceColors: ['#0ea5e9', '#38bdf8', '#06b6d4', '#67e8f9'],
    accentColor: '#38bdf8',
    textColor: '#e0f2fe',
    timerColor: '#38bdf8',
    headerBg: 'rgba(12,20,69,0.97)',
    particles: ['H⁺', 'OH⁻', 'pH', 'H₂O', 'HCl', 'NaOH', 'H₂SO₄', 'pH7', 'Ka', '🌊'],
    badge: '🧪',
  },
  {
    id: 'galaxy-atoms',
    name: 'Galaxy Atoms',
    nameAr: 'ذرات المجرة',
    emoji: '🌌',
    description: 'Space galaxy theme with orbiting electrons and cosmic chemistry',
    topic: 'Atomic Structure',
    bg: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    cardBg: 'rgba(15,12,41,0.92)',
    choiceColors: ['#a78bfa', '#c084fc', '#e879f9', '#818cf8'],
    accentColor: '#c084fc',
    textColor: '#f3e8ff',
    timerColor: '#c084fc',
    headerBg: 'rgba(15,12,41,0.97)',
    particles: ['⭐', '🌟', '✨', '💫', '🪐', '⚛️', '🌌', '🔭', '☄️', 'e⁻', 'p⁺', 'n⁰'],
    badge: '🌌',
  },
  {
    id: 'neon-lab',
    name: 'Neon Chemistry',
    nameAr: 'الكيمياء النيون',
    emoji: '⚡',
    description: 'Bright neon glowing colors — high energy electrochemistry vibes',
    topic: 'Electrochemistry',
    bg: 'linear-gradient(135deg, #0a0a0a 0%, #0d0d1a 50%, #0a0a14 100%)',
    cardBg: 'rgba(10,10,10,0.95)',
    choiceColors: ['#f0abfc', '#a78bfa', '#34d399', '#fbbf24'],
    accentColor: '#f0abfc',
    textColor: '#ffffff',
    timerColor: '#f0abfc',
    headerBg: 'rgba(5,5,5,0.98)',
    particles: ['⚡', '🔋', '⚡', 'e⁻', 'V', 'Ω', 'A', '⚡', 'Cu', 'Zn', 'Ag', '⚡'],
    badge: '⚡',
  },
  {
    id: 'equilibrium-scale',
    name: 'Equilibrium',
    nameAr: 'الاتزان الكيميائي',
    emoji: '⚖️',
    description: 'Calm purple-gold balance theme for equilibrium and Le Chatelier',
    topic: 'Chemical Equilibrium',
    bg: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4c1d95 100%)',
    cardBg: 'rgba(30,27,75,0.92)',
    choiceColors: ['#818cf8', '#a78bfa', '#fde68a', '#c4b5fd'],
    accentColor: '#fde68a',
    textColor: '#ede9fe',
    timerColor: '#fde68a',
    headerBg: 'rgba(30,27,75,0.97)',
    particles: ['⚖️', '⇌', 'Kc', 'Kp', '⇌', 'ΔG', 'Ka', 'Kb', '⚖️', '→', '←', '⇌'],
    badge: '⚖️',
  },
  {
    id: 'bubble-soft',
    name: 'Bubble Lab',
    nameAr: 'مختبر الفقاعات',
    emoji: '🫧',
    description: 'Soft pastel pink & mauve — perfect for any chemistry topic',
    topic: 'Any Topic',
    bg: 'linear-gradient(135deg, #1a0533 0%, #2d0a4e 50%, #1a1033 100%)',
    cardBg: 'rgba(26,5,51,0.92)',
    choiceColors: ['#f472b6', '#c084fc', '#fb7185', '#e879f9'],
    accentColor: '#f472b6',
    textColor: '#fdf4ff',
    timerColor: '#f472b6',
    headerBg: 'rgba(26,5,51,0.97)',
    particles: ['🫧', '🫧', '💜', '🫧', '✨', '🫧', '💗', '🫧', '🫧', '💜', '✨', '🫧'],
    badge: '🧪',
  },
  {
    id: 'thermodynamics',
    name: 'Energy Flow',
    nameAr: 'الطاقة والديناميكا الحرارية',
    emoji: '♨️',
    description: 'Warm amber and red for enthalpy, entropy and thermodynamics',
    topic: 'Thermodynamics',
    bg: 'linear-gradient(135deg, #1c1400 0%, #422006 50%, #713f12 100%)',
    cardBg: 'rgba(28,20,0,0.92)',
    choiceColors: ['#f59e0b', '#d97706', '#fbbf24', '#92400e'],
    accentColor: '#fbbf24',
    textColor: '#fef9c3',
    timerColor: '#fbbf24',
    headerBg: 'rgba(28,20,0,0.97)',
    particles: ['ΔH', 'ΔS', 'ΔG', 'T', 'q', 'w', '♨️', 'kJ', 'mol', 'K', 'ΔU', 'Cp'],
    badge: '♨️',
  },
  {
    id: 'candy-chem',
    name: 'Sweet Chemistry',
    nameAr: 'الكيمياء الحلوة',
    emoji: '🍭',
    description: 'Fun colorful candy theme — great for revision and practice games',
    topic: 'Revision / Practice',
    bg: 'linear-gradient(135deg, #1a0520 0%, #2d1040 50%, #1a0530 100%)',
    cardBg: 'rgba(26,5,32,0.92)',
    choiceColors: ['#fb923c', '#f472b6', '#a78bfa', '#34d399'],
    accentColor: '#f472b6',
    textColor: '#fdf4ff',
    timerColor: '#fb923c',
    headerBg: 'rgba(26,5,32,0.97)',
    particles: ['🍭', '⭐', '🌈', '✨', '🎉', '💫', '🍬', '⭐', '🎊', '🌟', '🍭', '✨'],
    badge: '🎉',
  },
];

export function getTemplate(id: string): GameTemplate {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
}
