export interface GameTemplate {
  id: string;
  name: string;
  nameAr: string;
  emoji: string;
  description: string;
  topic: string; // chemistry topic it suits
  bg: string;           // main background gradient
  cardBg: string;       // question card bg
  choiceColors: string[]; // 4 answer button colors
  accentColor: string;
  textColor: string;
  timerColor: string;
  headerBg: string;
  particles: string[];  // floating emoji decorations
  font?: string;
  badge: string;        // topic badge emoji
  category: string;
}

export const TEMPLATES: GameTemplate[] = [
  {
    id: 'periodic-table',
    name: 'Periodic Table Lab',
    nameAr: 'مختبر الجدول الدوري',
    emoji: '🔬',
    description: 'Dark scientific lab with periodic table elements floating around',
    topic: 'General Chemistry',
    bg: 'linear-gradient(135deg, #0a0a1a 0%, #0d1b2a 50%, #1a0a2e 100%)',
    cardBg: 'rgba(13,27,42,0.9)',
    choiceColors: ['#3b82f6', '#8b5cf6', '#06b6d4', '#6366f1'],
    accentColor: '#60a5fa',
    textColor: '#e2e8f0',
    timerColor: '#60a5fa',
    headerBg: 'rgba(10,10,26,0.95)',
    particles: ['H', 'He', 'Li', 'C', 'N', 'O', 'Na', 'Mg', 'Al', 'Si', 'Cl', 'K', 'Ca', 'Fe', 'Cu', 'Zn', 'Br', 'Au'],
    badge: '⚛️',
    category: 'science',
  },
  {
    id: 'organic-chemistry',
    name: 'Organic World',
    nameAr: 'عالم الكيمياء العضوية',
    emoji: '🌿',
    description: 'Green organic theme with carbon chains and molecular structures',
    topic: 'Organic Chemistry',
    bg: 'linear-gradient(135deg, #052e16 0%, #14532d 50%, #166534 100%)',
    cardBg: 'rgba(5,46,22,0.9)',
    choiceColors: ['#22c55e', '#16a34a', '#4ade80', '#86efac'],
    accentColor: '#4ade80',
    textColor: '#dcfce7',
    timerColor: '#4ade80',
    headerBg: 'rgba(5,46,22,0.95)',
    particles: ['CH₄', 'C₂H₆', '-OH', '-COOH', '-CHO', 'C=C', 'C≡C', 'R-', 'C₆H₆', 'CH₃'],
    badge: '🌿',
    category: 'science',
  },
  {
    id: 'fire-reactions',
    name: 'Reaction Fire',
    nameAr: 'نار التفاعلات',
    emoji: '🔥',
    description: 'Hot fiery theme for exothermic reactions and energy topics',
    topic: 'Thermodynamics / Reactions',
    bg: 'linear-gradient(135deg, #1c0500 0%, #7c1d06 50%, #c2410c 100%)',
    cardBg: 'rgba(28,5,0,0.92)',
    choiceColors: ['#ef4444', '#f97316', '#eab308', '#dc2626'],
    accentColor: '#fb923c',
    textColor: '#fef3c7',
    timerColor: '#fbbf24',
    headerBg: 'rgba(28,5,0,0.97)',
    particles: ['🔥', '💥', '⚡', '🌡️', '♨️', '🔥', '💨', '✨', '🌋', '⚗️'],
    badge: '🔥',
    category: 'science',
  },
  {
    id: 'ocean-acids',
    name: 'Ocean pH Lab',
    nameAr: 'مختبر الأحماض والقواعد',
    emoji: '🌊',
    description: 'Deep ocean blue for acids, bases and pH topics',
    topic: 'Acids & Bases',
    bg: 'linear-gradient(135deg, #0c1445 0%, #1e3a5f 50%, #0e4d7b 100%)',
    cardBg: 'rgba(12,20,69,0.9)',
    choiceColors: ['#0ea5e9', '#38bdf8', '#06b6d4', '#67e8f9'],
    accentColor: '#38bdf8',
    textColor: '#e0f2fe',
    timerColor: '#38bdf8',
    headerBg: 'rgba(12,20,69,0.97)',
    particles: ['H⁺', 'OH⁻', 'pH', 'H₂O', 'HCl', 'NaOH', 'H₂SO₄', 'pH7', 'Ka', '🌊'],
    badge: '🧪',
    category: 'science',
  },
  {
    id: 'galaxy-atoms',
    name: 'Galaxy Atoms',
    nameAr: 'ذرات المجرة',
    emoji: '🌌',
    description: 'Space galaxy theme with orbiting electrons and cosmic chemistry',
    topic: 'Atomic Structure',
    bg: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    cardBg: 'rgba(15,12,41,0.92)',
    choiceColors: ['#a78bfa', '#c084fc', '#e879f9', '#818cf8'],
    accentColor: '#c084fc',
    textColor: '#f3e8ff',
    timerColor: '#c084fc',
    headerBg: 'rgba(15,12,41,0.97)',
    particles: ['⭐', '🌟', '✨', '💫', '🪐', '⚛️', '🌌', '🔭', '☄️', 'e⁻', 'p⁺', 'n⁰'],
    badge: '🌌',
    category: 'science',
  },
  {
    id: 'neon-lab',
    name: 'Neon Chemistry',
    nameAr: 'الكيمياء النيون',
    emoji: '⚡',
    description: 'Bright neon glowing colors — high energy electrochemistry vibes',
    topic: 'Electrochemistry',
    bg: 'linear-gradient(135deg, #0a0a0a 0%, #0d0d1a 50%, #0a0a14 100%)',
    cardBg: 'rgba(10,10,10,0.95)',
    choiceColors: ['#f0abfc', '#a78bfa', '#34d399', '#fbbf24'],
    accentColor: '#f0abfc',
    textColor: '#ffffff',
    timerColor: '#f0abfc',
    headerBg: 'rgba(5,5,5,0.98)',
    particles: ['⚡', '🔋', '⚡', 'e⁻', 'V', 'Ω', 'A', '⚡', 'Cu', 'Zn', 'Ag', '⚡'],
    badge: '⚡',
    category: 'science',
  },
  {
    id: 'equilibrium-scale',
    name: 'Equilibrium',
    nameAr: 'الاتزان الكيميائي',
    emoji: '⚖️',
    description: 'Calm purple-gold balance theme for equilibrium and Le Chatelier',
    topic: 'Chemical Equilibrium',
    bg: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4c1d95 100%)',
    cardBg: 'rgba(30,27,75,0.92)',
    choiceColors: ['#818cf8', '#a78bfa', '#fde68a', '#c4b5fd'],
    accentColor: '#fde68a',
    textColor: '#ede9fe',
    timerColor: '#fde68a',
    headerBg: 'rgba(30,27,75,0.97)',
    particles: ['⚖️', '⇌', 'Kc', 'Kp', '⇌', 'ΔG', 'Ka', 'Kb', '⚖️', '→', '←', '⇌'],
    badge: '⚖️',
    category: 'science',
  },
  {
    id: 'bubble-soft',
    name: 'Bubble Lab',
    nameAr: 'مختبر الفقاعات',
    emoji: '🫧',
    description: 'Soft pastel pink & mauve — perfect for any chemistry topic',
    topic: 'Any Topic',
    bg: 'linear-gradient(135deg, #1a0533 0%, #2d0a4e 50%, #1a1033 100%)',
    cardBg: 'rgba(26,5,51,0.92)',
    choiceColors: ['#f472b6', '#c084fc', '#fb7185', '#e879f9'],
    accentColor: '#f472b6',
    textColor: '#fdf4ff',
    timerColor: '#f472b6',
    headerBg: 'rgba(26,5,51,0.97)',
    particles: ['🫧', '🫧', '💜', '🫧', '✨', '🫧', '💗', '🫧', '🫧', '💜', '✨', '🫧'],
    badge: '🧪',
    category: 'science',
  },
  {
    id: 'thermodynamics',
    name: 'Energy Flow',
    nameAr: 'الطاقة والديناميكا الحرارية',
    emoji: '♨️',
    description: 'Warm amber and red for enthalpy, entropy and thermodynamics',
    topic: 'Thermodynamics',
    bg: 'linear-gradient(135deg, #1c1400 0%, #422006 50%, #713f12 100%)',
    cardBg: 'rgba(28,20,0,0.92)',
    choiceColors: ['#f59e0b', '#d97706', '#fbbf24', '#92400e'],
    accentColor: '#fbbf24',
    textColor: '#fef9c3',
    timerColor: '#fbbf24',
    headerBg: 'rgba(28,20,0,0.97)',
    particles: ['ΔH', 'ΔS', 'ΔG', 'T', 'q', 'w', '♨️', 'kJ', 'mol', 'K', 'ΔU', 'Cp'],
    badge: '♨️',
    category: 'science',
  },
  {
    id: 'candy-chem',
    name: 'Sweet Chemistry',
    nameAr: 'الكيمياء الحلوة',
    emoji: '🍭',
    description: 'Fun colorful candy theme — great for revision and practice games',
    topic: 'Revision / Practice',
    bg: 'linear-gradient(135deg, #1a0520 0%, #2d1040 50%, #1a0530 100%)',
    cardBg: 'rgba(26,5,32,0.92)',
    choiceColors: ['#fb923c', '#f472b6', '#a78bfa', '#34d399'],
    accentColor: '#f472b6',
    textColor: '#fdf4ff',
    timerColor: '#fb923c',
    headerBg: 'rgba(26,5,32,0.97)',
    particles: ['🍭', '⭐', '🌈', '✨', '🎉', '💫', '🍬', '⭐', '🎊', '🌟', '🍭', '✨'],
    badge: '🎉',
    category: 'science',
  },
  {
    id: 'ice-crystal',
    name: 'Ice Crystal Lab',
    nameAr: 'مختبر بلورات الثلج',
    emoji: '❄️',
    description: 'Icy blue-white crystal theme for states of matter, bonds and intermolecular forces',
    topic: 'States of Matter / Bonding',
    bg: 'linear-gradient(135deg, #0a1628 0%, #0e2a4a 50%, #102040 100%)',
    cardBg: 'rgba(10,22,40,0.92)',
    choiceColors: ['#bae6fd', '#7dd3fc', '#38bdf8', '#e0f2fe'],
    accentColor: '#bae6fd',
    textColor: '#f0f9ff',
    timerColor: '#7dd3fc',
    headerBg: 'rgba(10,22,40,0.97)',
    particles: ['❄️', '🧊', '❄️', 'H₂O', '❄️', 'ICE', '❄️', '🌨️', 'ΔHfus', '❄️', 'mp', '❄️'],
    badge: '❄️',
    category: 'science',
  },
  {
    id: 'neon-night',
    name: 'Neon Night',
    nameAr: 'ليل النيون',
    emoji: '🌃',
    description: 'Electric neon glow on pitch black — high-energy competitive battles',
    topic: 'Any Topic',
    bg: 'linear-gradient(135deg, #000000 0%, #0a0014 50%, #000a0a 100%)',
    cardBg: 'rgba(0,0,10,0.95)',
    choiceColors: ['#ff00ff', '#00ffff', '#ff6600', '#00ff88'],
    accentColor: '#ff00ff',
    textColor: '#ffffff',
    timerColor: '#00ffff',
    headerBg: 'rgba(0,0,0,0.98)',
    particles: ['⚡', '🔮', '✨', '💥', '⚡', '🌟', '💫', '⚡', '✨', '🔮', '⚡', '💥'],
    badge: '⚡',
    category: 'science',
  },
  {
    id: 'desert-sand',
    name: 'Desert Minerals',
    nameAr: 'معادن الصحراء',
    emoji: '🏜️',
    description: 'Warm sand and gold tones for minerals, salts and inorganic chemistry',
    topic: 'Inorganic / Minerals',
    bg: 'linear-gradient(135deg, #1c1007 0%, #3d2406 50%, #5c3d11 100%)',
    cardBg: 'rgba(28,16,7,0.92)',
    choiceColors: ['#fbbf24', '#d97706', '#f59e0b', '#92400e'],
    accentColor: '#fcd34d',
    textColor: '#fefce8',
    timerColor: '#fcd34d',
    headerBg: 'rgba(28,16,7,0.97)',
    particles: ['NaCl', 'CaCO₃', 'SiO₂', 'MgO', 'Al₂O₃', 'FeO', 'KNO₃', 'ZnS', 'Cu₂O', 'BaSO₄', 'PbS', 'SnO'],
    badge: '🏜️',
    category: 'science',
  },
  {
    id: 'radioactive',
    name: 'Nuclear Lab',
    nameAr: 'المختبر النووي',
    emoji: '☢️',
    description: 'Radioactive green warning theme — perfect for nuclear chemistry and radioactivity topics',
    topic: 'Nuclear Chemistry',
    bg: 'linear-gradient(135deg, #0a1a00 0%, #0f2d00 50%, #091500 100%)',
    cardBg: 'rgba(10,26,0,0.93)',
    choiceColors: ['#4ade80', '#86efac', '#22c55e', '#16a34a'],
    accentColor: '#4ade80',
    textColor: '#f0fdf4',
    timerColor: '#86efac',
    headerBg: 'rgba(10,26,0,0.97)',
    particles: ['☢️', 'α', 'β', 'γ', '⚛️', 'n', 'U-235', 'Rn', 't½', 'MeV', 'Ra', '☢️'],
    badge: '☢️',
    category: 'science',
  },
  {
    id: 'violet-galaxy',
    name: 'Violet Galaxy',
    nameAr: 'مجرة البنفسج',
    emoji: '🔮',
    description: 'Deep violet and magenta galaxy — beautiful for any chemistry topic',
    topic: 'Any Topic',
    bg: 'linear-gradient(135deg, #12002e 0%, #1e0050 50%, #0a0020 100%)',
    cardBg: 'rgba(18,0,46,0.92)',
    choiceColors: ['#d946ef', '#a855f7', '#ec4899', '#8b5cf6'],
    accentColor: '#d946ef',
    textColor: '#fdf4ff',
    timerColor: '#a855f7',
    headerBg: 'rgba(12,0,30,0.97)',
    particles: ['🔮', '✨', '💜', '🌌', '⭐', '💫', '🔮', '🌟', '💎', '✨', '🔮', '💜'],
    badge: '🔮',
    category: 'science',
  },
  // ── Mathematics ──────────────────────────────────────────────────────────────
  {
    id: 'algebra-grid',
    name: 'Algebra Grid',
    nameAr: 'شبكة الجبر',
    emoji: '📐',
    description: 'Dark grid with equations and variables floating around',
    topic: 'Algebra / Equations',
    bg: 'linear-gradient(135deg, #0a0f1e 0%, #0f1f3d 50%, #0a1628 100%)',
    cardBg: 'rgba(10,15,30,0.92)',
    choiceColors: ['#3b82f6','#6366f1','#a78bfa','#22d3ee'],
    accentColor: '#6366f1',
    textColor: '#e2e8f0',
    timerColor: '#6366f1',
    headerBg: 'rgba(10,15,30,0.97)',
    particles: ['x²','y=mx','∫','∑','π','√','≠','∞','dx','Δ','f(x)','→'],
    badge: '📐',
    category: 'math',
  },
  {
    id: 'geometry-shapes',
    name: 'Geometry World',
    nameAr: 'عالم الهندسة',
    emoji: '📏',
    description: 'Colorful geometric shapes and angles',
    topic: 'Geometry / Shapes',
    bg: 'linear-gradient(135deg, #0d0523 0%, #1a0840 50%, #0d0523 100%)',
    cardBg: 'rgba(13,5,35,0.92)',
    choiceColors: ['#f472b6','#a78bfa','#34d399','#fbbf24'],
    accentColor: '#a78bfa',
    textColor: '#fdf4ff',
    timerColor: '#f472b6',
    headerBg: 'rgba(13,5,35,0.97)',
    particles: ['△','□','○','◇','∠90°','π r²','∥','⊥','360°','⬡','★','✦'],
    badge: '📏',
    category: 'math',
  },
  {
    id: 'numbers-fun',
    name: 'Numbers & Stats',
    nameAr: 'الأرقام والإحصاء',
    emoji: '🔢',
    description: 'Bright teal and orange for numbers, statistics and data',
    topic: 'Statistics / Numbers',
    bg: 'linear-gradient(135deg, #001a1a 0%, #003333 50%, #001f1f 100%)',
    cardBg: 'rgba(0,26,26,0.92)',
    choiceColors: ['#06b6d4','#10b981','#f59e0b','#84cc16'],
    accentColor: '#06b6d4',
    textColor: '#ccfbf1',
    timerColor: '#10b981',
    headerBg: 'rgba(0,26,26,0.97)',
    particles: ['1','2','3','%','÷','×','+','-','=','∑','μ','σ'],
    badge: '🔢',
    category: 'math',
  },
  {
    id: 'calculus-wave',
    name: 'Calculus Wave',
    nameAr: 'موجة حساب التفاضل',
    emoji: '📈',
    description: 'Flowing curves and derivatives on dark blue',
    topic: 'Calculus / Functions',
    bg: 'linear-gradient(135deg, #000820 0%, #001040 50%, #000c30 100%)',
    cardBg: 'rgba(0,8,32,0.93)',
    choiceColors: ['#38bdf8','#818cf8','#c084fc','#34d399'],
    accentColor: '#38bdf8',
    textColor: '#e0f2fe',
    timerColor: '#38bdf8',
    headerBg: 'rgba(0,8,32,0.97)',
    particles: ['d/dx','∫f(x)','lim','dy',"f'(x)",'∂','∇','→∞','sin','cos','tan','e^x'],
    badge: '📈',
    category: 'math',
  },
  // ── Languages ─────────────────────────────────────────────────────────────────
  {
    id: 'arabic-calligraphy',
    name: 'Arabic World',
    nameAr: 'عالم اللغة العربية',
    emoji: '🌙',
    description: 'Rich deep red and gold Arabic calligraphy theme',
    topic: 'Arabic Language',
    bg: 'linear-gradient(135deg, #1a0005 0%, #3b000a 50%, #1a0010 100%)',
    cardBg: 'rgba(26,0,5,0.93)',
    choiceColors: ['#f87171','#fbbf24','#a78bfa','#fb923c'],
    accentColor: '#fbbf24',
    textColor: '#fef9c3',
    timerColor: '#fbbf24',
    headerBg: 'rgba(26,0,5,0.97)',
    particles: ['ع','ر','ب','ي','ة','☪️','🌙','✨','📖','ق','ص','و'],
    badge: '🌙',
    category: 'language',
  },
  {
    id: 'english-library',
    name: 'English Library',
    nameAr: 'مكتبة اللغة الإنجليزية',
    emoji: '📚',
    description: 'Classic dark wood library aesthetic for English language',
    topic: 'English Language',
    bg: 'linear-gradient(135deg, #0f0800 0%, #2a1800 50%, #1a1000 100%)',
    cardBg: 'rgba(15,8,0,0.93)',
    choiceColors: ['#d97706','#92400e','#b45309','#78350f'],
    accentColor: '#fbbf24',
    textColor: '#fefce8',
    timerColor: '#d97706',
    headerBg: 'rgba(15,8,0,0.97)',
    particles: ['A','B','C','abc','✏️','📖','📝','🔤','📚','Aa','Bb','Cc'],
    badge: '📚',
    category: 'language',
  },
  {
    id: 'french-paris',
    name: 'French & Paris',
    nameAr: 'اللغة الفرنسية',
    emoji: '🗼',
    description: 'Elegant blue and gold French theme',
    topic: 'French Language',
    bg: 'linear-gradient(135deg, #00001f 0%, #000040 50%, #001a00 100%)',
    cardBg: 'rgba(0,0,31,0.93)',
    choiceColors: ['#3b82f6','#ef4444','#f9fafb','#fbbf24'],
    accentColor: '#60a5fa',
    textColor: '#eff6ff',
    timerColor: '#60a5fa',
    headerBg: 'rgba(0,0,31,0.97)',
    particles: ['Bonjour','Merci','Oui','🗼','🥐','Non','📖','🇫🇷','à','é','ê','ç'],
    badge: '🗼',
    category: 'language',
  },
  {
    id: 'literature-poetry',
    name: 'Poetry & Lit',
    nameAr: 'الشعر والأدب',
    emoji: '🖊️',
    description: 'Deep purple and soft gold for literature and poetry',
    topic: 'Literature / Poetry',
    bg: 'linear-gradient(135deg, #12001f 0%, #1e0035 50%, #12001f 100%)',
    cardBg: 'rgba(18,0,31,0.93)',
    choiceColors: ['#c084fc','#e879f9','#818cf8','#f472b6'],
    accentColor: '#c084fc',
    textColor: '#fdf4ff',
    timerColor: '#e879f9',
    headerBg: 'rgba(18,0,31,0.97)',
    particles: ['✍️','📜','🖊️','✨','📖','🌹','💜','🎭','📝','⭐','🌙','🖊️'],
    badge: '🖊️',
    category: 'language',
  },
  // ── Sciences ──────────────────────────────────────────────────────────────────
  {
    id: 'biology-cells',
    name: 'Biology Lab',
    nameAr: 'مختبر الأحياء',
    emoji: '🦠',
    description: 'Living green cell theme for biology topics',
    topic: 'Biology',
    bg: 'linear-gradient(135deg, #001a00 0%, #003300 50%, #001a08 100%)',
    cardBg: 'rgba(0,26,0,0.93)',
    choiceColors: ['#4ade80','#86efac','#a3e635','#22d3ee'],
    accentColor: '#4ade80',
    textColor: '#f0fdf4',
    timerColor: '#86efac',
    headerBg: 'rgba(0,26,0,0.97)',
    particles: ['🦠','🧬','DNA','RNA','🔬','ATP','🌿','mitosis','cell','🧫','🫀','🫁'],
    badge: '🦠',
    category: 'science',
  },
  {
    id: 'physics-waves',
    name: 'Physics Lab',
    nameAr: 'مختبر الفيزياء',
    emoji: '⚛️',
    description: 'Electric blue physics theme with forces and waves',
    topic: 'Physics',
    bg: 'linear-gradient(135deg, #000a20 0%, #001040 50%, #000820 100%)',
    cardBg: 'rgba(0,10,32,0.93)',
    choiceColors: ['#38bdf8','#22d3ee','#818cf8','#34d399'],
    accentColor: '#38bdf8',
    textColor: '#e0f2fe',
    timerColor: '#22d3ee',
    headerBg: 'rgba(0,10,32,0.97)',
    particles: ['F=ma','E=mc²','v=fλ','hf','⚡','🌊','🔭','m/s²','J','W','Hz','N'],
    badge: '⚛️',
    category: 'science',
  },
  {
    id: 'earth-science',
    name: 'Earth Science',
    nameAr: 'علوم الأرض',
    emoji: '🌍',
    description: 'Blue-green Earth and environment theme',
    topic: 'Earth Science / Environment',
    bg: 'linear-gradient(135deg, #001a0a 0%, #002a10 50%, #000f20 100%)',
    cardBg: 'rgba(0,26,10,0.93)',
    choiceColors: ['#10b981','#3b82f6','#84cc16','#06b6d4'],
    accentColor: '#10b981',
    textColor: '#ecfdf5',
    timerColor: '#3b82f6',
    headerBg: 'rgba(0,26,10,0.97)',
    particles: ['🌍','🌊','🌋','🏔️','☁️','💧','🌿','🔥','🌞','❄️','🌈','🌱'],
    badge: '🌍',
    category: 'science',
  },
];

export function getTemplate(id: string): GameTemplate {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
}
